### ISSUE TITLE
In case gender_concept_id = 0 (unidentified gender)

### ISSUE THREAD

**Issue by Mainguthing** [OHDSI/CohortIncidence#10]
I have tested the newly added demographic stratification function. It seems to work well, but then I noticed subjects with gender_concept_id=0 were still taken into account when IR was calculated. 
Should the package somehow exclude those as well, or should this step be already taken care of at the ELT step?

**Comment by chrisknoll** [comment]
No:  if you want to exclude people from analysis, you should remove them from the cohorts.
