### ISSUE TITLE
Import / Run cohort via json or csv

### ISSUE THREAD

**Issue by jmt0816** [OHDSI/CohortIncidence#28]
Is there any functionality that is planned to be able to run this package as a stand alone? I.e. taking a json or csv and running directly without the use of Atlas?

Is there a work around?

**Comment by chrisknoll** [comment]
This hasn't been integrated into Atlas/WebAPI (there already is a simpler IR function in WebAPI).   The design strategy was you implement as Java and wrap in R if you want to use it stand-alone.  

It's your lucky day! There's an R wrapper for this!   Checkout the [vignette](https://ohdsi.github.io/CohortIncidence/articles/using-cohortincidence.html).
