### ISSUE TITLE
Provide function for computing cohort incidence?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortIncidence#8]
Although I appreciate how lightweight this package currently is (made possible because the analytics are all SQL, no R), it might be helpful for the users to provide a function that actually computes the cohort incidence. This would also be more in line with other HADES packages. For example, CohortMethod provides functions that execute the comparative cohort design, they don't provide the user with SQL. 

Such a function would take the usual parameters as input, such as `connnectionDetails` and `cohortTables`, as well as the incidence rate specifications, and return an R object with the incidence rates. The table containing the output on the server could even be instantiated as a temp table for this function.

**Comment by chrisknoll** [comment]
Sure.  I've implemented temp table mode in PR #7.  I did want to limit the dependencies on this package, so to do what you ask, it means we need DatabaseConnector and SqlRender.  For testing, I'll need to look at how to incorporate Enomia package for tests.   

But what you're asking for is not impossible, so let me see if I an address sit before the next release.

**Comment by chrisknoll** [comment]
I've implemented your request on the `issue-8` branch: https://github.com/OHDSI/CohortIncidence/tree/issue-8

Please try to install from this branch and tell me if it suits your needs.

The vignette was updated to demonstrate the useage.
